/**
 * ADF Compiler — renders modular .ai/*.adf source trees to flat vendor agent-config files.
 *
 * "Babel for agent configs" — ADF is the source of truth, vendor files are build artifacts.
 *
 * Architecture: pure core with no runtime dependencies (zero-dep package constraint).
 * - All I/O is injected (readFile), so the module is fully testable without touching disk.
 * - Output is deterministic: same inputs → byte-identical output.
 *
 * Zod validation lives at the CLI boundary (adf-compile.ts), not here.
 */

import type { AdfSection, AdfContent, Manifest, ManifestModule } from './types';
import { parseAdf } from './parser';
import { parseManifest } from './manifest';

// ============================================================================
// Target types
// ============================================================================

export type CompileTarget = 'claude' | 'agents' | 'cursor' | 'gemini';

export const COMPILE_TARGETS: CompileTarget[] = ['claude', 'agents', 'cursor', 'gemini'];

export interface CompileOptions {
  /** Target vendor format */
  target: CompileTarget;
  /** Base directory for resolving module paths (e.g. '.ai') */
  aiDir: string;
  /** File reader injection — allows DI for testing without disk access */
  readFile: (path: string) => string;
}

// ============================================================================
// Per-target config (divergence surface — easy to extend later)
// ============================================================================

interface TargetConfig {
  /** Heading text used as the top-level # title */
  title: string;
  /** Comment style for the generated banner */
  commentStyle: 'html' | 'hash';
}

const TARGET_CONFIGS: Record<CompileTarget, TargetConfig> = {
  claude: {
    title: 'CLAUDE.md',
    commentStyle: 'html',
  },
  agents: {
    title: 'AGENTS.md',
    commentStyle: 'html',
  },
  cursor: {
    title: '.cursorrules',
    commentStyle: 'hash',
  },
  gemini: {
    title: 'GEMINI.md',
    commentStyle: 'html',
  },
};

/** Filename on disk for each target (used by --write and --check). */
export const TARGET_FILENAMES: Record<CompileTarget, string> = {
  claude: 'CLAUDE.md',
  agents: 'AGENTS.md',
  cursor: '.cursorrules',
  gemini: 'GEMINI.md',
};

// ============================================================================
// Banner
// ============================================================================

const BANNER_BODY = 'GENERATED by charter adf compile — DO NOT EDIT. Source of truth: .ai/ modules. Re-run: charter adf compile --target all --write';

/**
 * The exact string that marks a file as a compile artifact.
 * Used for overwrite-protection checks — a file lacking this string is treated
 * as hand-written and --force is required to overwrite.
 */
export const COMPILE_BANNER_MARKER = 'GENERATED by charter adf compile';

export function buildBanner(style: 'html' | 'hash'): string {
  if (style === 'hash') {
    return `# ${BANNER_BODY}`;
  }
  return `<!-- ${BANNER_BODY} -->`;
}

// ============================================================================
// Compile result
// ============================================================================

export interface CompileResult {
  target: CompileTarget;
  output: string;
  defaultModules: string[];
  onDemandModules: ManifestModule[];
}

// ============================================================================
// Core compiler
// ============================================================================

/**
 * Compile the .ai/ module tree to a flat vendor agent-config string.
 *
 * Pure function — all I/O is injected via options.readFile.
 * Deterministic: same inputs → byte-identical output.
 */
export function compileAdf(options: CompileOptions): CompileResult {
  const { target, aiDir, readFile } = options;

  // Load and parse manifest
  const manifestPath = joinPath(aiDir, 'manifest.adf');
  const manifestContent = readFile(manifestPath);
  const manifestDoc = parseAdf(manifestContent);
  const manifest = parseManifest(manifestDoc);

  // Collect sections from all default-load modules in declaration order
  const defaultSections: AdfSection[] = [];
  for (const modPath of manifest.defaultLoad) {
    const fullPath = joinPath(aiDir, modPath);
    const content = readFile(fullPath);
    const doc = parseAdf(content);
    defaultSections.push(...doc.sections);
  }

  const config = TARGET_CONFIGS[target];
  const output = renderToVendorFormat(config, manifest, defaultSections, manifest.onDemand);

  return {
    target,
    output,
    defaultModules: manifest.defaultLoad,
    onDemandModules: manifest.onDemand,
  };
}

// ============================================================================
// Renderer
// ============================================================================

function renderToVendorFormat(
  config: TargetConfig,
  manifest: Manifest,
  defaultSections: AdfSection[],
  onDemandModules: ManifestModule[],
): string {
  const lines: string[] = [];

  // Banner (first line)
  lines.push(buildBanner(config.commentStyle));
  lines.push('');

  // Title
  lines.push(`# ${config.title}`);
  lines.push('');

  // Role / description from manifest if present
  if (manifest.role) {
    lines.push(`> ${manifest.role}`);
    lines.push('');
  }

  // Default module content — sections in declaration order
  for (const section of defaultSections) {
    const rendered = renderSection(section);
    if (rendered) {
      lines.push(rendered);
      lines.push('');
    }
  }

  // On-demand modules index (listing only — bodies NOT inlined)
  if (onDemandModules.length > 0) {
    lines.push('## On-demand modules');
    lines.push('');
    lines.push('Load the following modules by reading `.ai/<module>.adf` when the listed triggers match your task.');
    lines.push('');

    for (const mod of onDemandModules) {
      const triggerStr = mod.triggers.length > 0
        ? ` — triggers: ${mod.triggers.join(', ')}`
        : '';
      lines.push(`- \`${mod.path}\`${triggerStr}`);
    }
    lines.push('');
  }

  // Normalize trailing whitespace: exactly one trailing newline
  while (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }
  lines.push('');

  return lines.join('\n');
}

// ============================================================================
// Section → Markdown rendering
// ============================================================================

/**
 * Sections that are manifest routing plumbing — skipped during content rendering.
 *
 * These keys are structural directives (what to load, when, and with what budget)
 * rather than agent-facing rules. They appear in manifest.adf but the same key
 * can legitimately appear in module .adf files with different semantics (e.g.,
 * METRICS in a module is a measurement, not a file pointer map).
 *
 * We exclude keys that only make sense as manifest routing metadata and have no
 * agent-rule meaning in a flat vendor file:
 *   - DEFAULT_LOAD / ON_DEMAND: module lists (rendered separately in the on-demand index)
 *   - RULES: manifest-level routing rules, not agent constraints
 *   - BUDGET / SYNC / CADENCE: plumbing directives
 *
 * Keys like CONTEXT, CONSTRAINTS, METRICS, STATE, TASK, ROLE come from the
 * *module* files and carry real content — they are rendered normally.
 */
const MANIFEST_PLUMBING_KEYS = new Set([
  'DEFAULT_LOAD',
  'ON_DEMAND',
  'BUDGET',
  'SYNC',
  'CADENCE',
  'RULES',
]);

function renderSection(section: AdfSection): string | null {
  if (MANIFEST_PLUMBING_KEYS.has(section.key)) return null;

  const lines: string[] = [];

  // Section heading — append weight classification if annotated
  const weightSuffix = section.weight ? ` _(${section.weight})_` : '';
  lines.push(`## ${section.key}${weightSuffix}`);
  lines.push('');

  const bodyLines = renderContent(section.content);
  if (bodyLines.length > 0) {
    lines.push(...bodyLines);
  }

  // Strip trailing blank lines within this section block
  while (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop();
  }

  return lines.join('\n');
}

function renderContent(content: AdfContent): string[] {
  switch (content.type) {
    case 'text': {
      if (!content.value) return [];
      return content.value.split('\n');
    }
    case 'list': {
      return content.items.map(item => `- ${item}`);
    }
    case 'map': {
      return content.entries.map(e => `- **${e.key}**: ${e.value}`);
    }
    case 'metric': {
      return content.entries.map(e =>
        `- \`${e.key}\`: ${e.value} / ${e.ceiling} [${e.unit}]`
      );
    }
  }
}

// ============================================================================
// Helpers
// ============================================================================

function joinPath(base: string, relative: string): string {
  if (base.endsWith('/')) return base + relative;
  return base + '/' + relative;
}
