/**
 * Content Classifier — rule-routing decision tree for ADF migration.
 *
 * Classifies markdown elements into ADF sections (CONSTRAINTS, CONTEXT, ADVISORY)
 * with STAY/MIGRATE routing decisions. Uses deterministic heuristics, no LLM calls.
 */

import type { MarkdownSection, MarkdownElement } from './markdown-parser';
import type { AdfDocument } from './types';

// ============================================================================
// Types
// ============================================================================

export type RouteDecision = 'STAY' | 'MIGRATE';

export type AdfTargetSection = 'CONSTRAINTS' | 'CONTEXT' | 'ADVISORY';

export type WeightTag = 'load-bearing' | 'advisory';

/** Module path → lowercase trigger keywords for content-based routing. */
export type TriggerMap = Record<string, string[]>;

/** Optional overrides for classification heuristics. */
export interface ClassifierConfig {
  stayPatterns?: RegExp[];
  headingRoutes?: Array<{ pattern: RegExp; module: string }>;
}

export interface RoutingTrace {
  /** What headingToModule() returned before content-based fallback. */
  headingModule: string;
  /** Set when a phrase-level QA override fired instead of keyword scoring. */
  phraseOverride?: string;
  /** Per-module keyword match score from the triggerMap scoring pass. */
  candidateScores: Record<string, number>;
}

export interface ClassificationResult {
  decision: RouteDecision;
  targetSection: AdfTargetSection;
  targetModule: string;
  weight: WeightTag;
  reason: string;
  /** Populated when content-based routing ran. Opt-in observability for #46. */
  routingTrace?: RoutingTrace;
}

export interface MigrationItem {
  element: MarkdownElement;
  sourceHeading: string;
  classification: ClassificationResult;
}

export interface MigrationPlan {
  items: MigrationItem[];
  stayItems: MigrationItem[];
  migrateItems: MigrationItem[];
  targetModules: string[];
  summary: {
    constraints: number;
    context: number;
    advisory: number;
    stay: number;
    total: number;
  };
}

// ============================================================================
// STAY Patterns — env/runtime content that should remain in vendor file
// ============================================================================

const STAY_PATTERNS: RegExp[] = [
  /\bWSL\b/i,
  /\bline.ending/i,
  /\bcredential.helper/i,
  /\b\/mnt\/c\//i,
  /\bwindows\b/i,
  /\bmingw/i,
  /\bPATH\s+issues?\s+in\s+WSL\b/i,
  /\bos[- ]specific\b/i,
  /\bshell[- ]specific\b/i,
];

const META_PATTERNS: RegExp[] = [
  /\bthis file is (?:auto-)?managed by/i,
  /\bdo not (?:edit|modify) this file/i,
  /\bauto-generated by charter/i,
  /\brules live in \.ai\//i,
  /\bsee \.ai\/manifest\.adf/i,
  /\bpre-charter\b/i,
  /\bwhen (?:stackbilt)?charter is bootstrapped/i,
];

// ============================================================================
// Classification Helpers
// ============================================================================

function matchesStayPattern(text: string, patterns: RegExp[] = STAY_PATTERNS): boolean {
  return patterns.some(p => p.test(text));
}

function matchesMetaPattern(text: string): boolean {
  return META_PATTERNS.some(p => p.test(text));
}

/**
 * Map a heading name to the most appropriate ADF target module.
 */
function headingToModule(heading: string, routes?: ClassifierConfig['headingRoutes']): string {
  const lower = heading.toLowerCase();

  if (routes) {
    for (const route of routes) {
      if (route.pattern.test(lower)) return route.module;
    }
    return 'core.adf';
  }

  if (/\b(design.system|ui|frontend|css|component|react|vue|svelte|next|nextjs|tailwind|shadcn|radix|storybook|vite|vitest|playwright|remix|nuxt|astro)\b/.test(lower)) {
    return 'frontend.adf';
  }
  if (/\b(qa|quality|test|testing|verification|validate|validation|contract|smoke|evidence|audit)\b/.test(lower)) {
    return 'qa.adf';
  }
  if (/\b(auth|authentication|authorization|security|secret|token|permission|cors|rate.limit|jwt|oauth|clerk|nextauth|lucia|session|cookie|csrf|xss|password|bcrypt)\b/.test(lower)) {
    return 'security.adf';
  }
  if (/\b(deploy|deployment|infrastructure|infra|ci|cd|pipeline|config|configuration|environment|env|docker|wrangler|cloudflare|vercel|netlify|railway|fly|render|github.actions|kv|d1|r2|queue|durable.object)\b/.test(lower)) {
    return 'infra.adf';
  }
  if (/\b(api|backend|server|database|db|endpoint|query|migration|handler|prisma|drizzle|mongoose|postgres|postgresql|mysql|sqlite|express|fastify|hono|trpc|zod|graphql)\b/.test(lower)) {
    return 'backend.adf';
  }
  return 'core.adf';
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Phrase-level QA patterns that signal verification/testing intent even when
 * infra or backend keywords coexist in the same bullet (fixes #44, #45).
 *
 * These fire BEFORE trigger-keyword scoring and route to qa.adf when that
 * module is present in the manifest's triggerMap.
 */
const QA_PHRASE_PATTERNS: RegExp[] = [
  /\bsmoke[\s-]tests?\b/i,
  /\bcontract[\s-]tests?\b/i,
  /\bschema[\s-]compat/i,
  /\bapproval[\s-]gat/i,          // "approval gate", "approval gating"
  /\bverified\s+against\b/i,
  /\btest[\s-]fixtures?\b/i,
];

/**
 * Return the override module if strong QA phrase patterns are detected, else null.
 * Callers must confirm the override module exists in the triggerMap before using it.
 */
function contentRouteOverride(text: string): string | null {
  if (QA_PHRASE_PATTERNS.some(p => p.test(text))) return 'qa.adf';
  return null;
}

/**
 * Content-based fallback routing. When heading-based routing returns core.adf,
 * scan element content against ON_DEMAND trigger keywords from the manifest.
 *
 * Returns the winning module plus a score map and optional phrase-override for
 * routing observability (#46).
 */
function contentToModule(
  text: string,
  triggerMap: TriggerMap,
): { module: string; phraseOverride?: string; scores: Record<string, number> } {
  const lower = text.toLowerCase();
  const scores: Record<string, number> = {};

  // Phrase-level override: high-signal compound patterns beat keyword counting.
  // Only fires when the override module is actually in the manifest triggerMap.
  const override = contentRouteOverride(text);
  if (override && override in triggerMap) {
    scores[override] = Infinity; // sentinel — phrase match beats all trigger scores
    return { module: override, phraseOverride: override, scores };
  }

  let bestModule = 'core.adf';
  let bestScore = 0;
  let bestSpecificity = 0;

  for (const [module, triggers] of Object.entries(triggerMap)) {
    let score = 0;
    let specificity = 0;

    for (const trigger of triggers) {
      // Match whole words or common suffixes (s, ed, ing, ment, tion, ity, ication).
      // This allows "token" → "tokens", "deploy" → "deploying"/"deployment",
      // "auth" → "authentication" — while blocking "author", "apiary", "authority".
      if (new RegExp(`\\b${escapeRegex(trigger)}(?:s|ed|ing|ment|tion|ity|ication)?\\b`, 'i').test(lower)) {
        score++;
        specificity = Math.max(specificity, trigger.length);
      }
    }

    scores[module] = score;

    if (score > bestScore || (score === bestScore && specificity > bestSpecificity)) {
      bestModule = module;
      bestScore = score;
      bestSpecificity = specificity;
    }
  }

  return { module: bestModule, scores };
}

// ============================================================================
// Element Classification
// ============================================================================

/**
 * Classify a single markdown element into an ADF routing decision.
 */
export function classifyElement(
  element: MarkdownElement,
  heading: string,
  triggerMap?: TriggerMap,
  config?: ClassifierConfig,
): ClassificationResult {
  const text = element.content;
  const headingModule = headingToModule(heading, config?.headingRoutes);
  let module = headingModule;
  let routingTrace: RoutingTrace | undefined;

  // Content-based routing: check element content against ON_DEMAND trigger
  // keywords from the manifest. When heading routes to core.adf, always apply.
  // When heading routes elsewhere, still check — if content scores ≥2 for a
  // different module, let content routing win (#88: prevents on-demand modules
  // from staying as empty scaffolds when content clearly belongs there).
  if (triggerMap) {
    const { module: contentModule, phraseOverride, scores } = contentToModule(text, triggerMap);
    if (module === 'core.adf') {
      module = contentModule;
    } else if (contentModule !== 'core.adf' && contentModule !== module && (scores[contentModule] ?? 0) >= 2) {
      module = contentModule;
    }
    routingTrace = { headingModule, phraseOverride, candidateScores: scores };
  }

  // Check STAY patterns first
  if (matchesStayPattern(text, config?.stayPatterns)) {
    return {
      decision: 'STAY',
      targetSection: 'CONTEXT',
      targetModule: module,
      weight: 'advisory',
      reason: 'Environment/runtime-specific (STAY in vendor file)',
      routingTrace,
    };
  }

  // Meta-comments: self-referential instructions that should not migrate
  if (matchesMetaPattern(text)) {
    return {
      decision: 'STAY',
      targetSection: 'CONTEXT',
      targetModule: module,
      weight: 'advisory',
      reason: 'Meta-comment (self-referential, skip)',
      routingTrace,
    };
  }

  // Heading-context guard: documentation/reference headings should route to
  // CONTEXT even when content contains imperative keywords (#86).
  const isDocHeading = /\b(reference|constant|metric|format|example|glossary|api|endpoint|schema|overview|summary|description|note)\b/i.test(heading);

  // Route by element type and strength
  switch (element.type) {
    case 'rule': {
      if (element.strength === 'imperative' && !isDocHeading) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONSTRAINTS',
          targetModule: module,
          weight: 'load-bearing',
          reason: 'Imperative rule (NEVER/ALWAYS/MUST)',
          routingTrace,
        };
      }
      if (element.strength === 'imperative' && isDocHeading) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONTEXT',
          targetModule: module,
          weight: 'advisory',
          reason: 'Imperative keyword in documentation heading — treated as reference (#86)',
          routingTrace,
        };
      }
      if (element.strength === 'advisory') {
        return {
          decision: 'MIGRATE',
          targetSection: 'ADVISORY',
          targetModule: module,
          weight: 'advisory',
          reason: 'Advisory rule (prefer/should/bias)',
          routingTrace,
        };
      }
      // Neutral rules — check heading context for more signal
      if (/\b(convention|style|naming|format)\b/i.test(heading)) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONSTRAINTS',
          targetModule: module,
          weight: 'advisory',
          reason: 'Naming/style convention',
          routingTrace,
        };
      }
      if (/\b(git|commit|workflow|hook)\b/i.test(heading)) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONSTRAINTS',
          targetModule: module,
          weight: 'load-bearing',
          reason: 'Git workflow rule',
          routingTrace,
        };
      }
      // Default neutral rule → CONSTRAINTS advisory
      return {
        decision: 'MIGRATE',
        targetSection: 'CONSTRAINTS',
        targetModule: module,
        weight: 'advisory',
        reason: 'Rule (neutral strength)',
        routingTrace,
      };
    }

    case 'code-block': {
      return {
        decision: 'MIGRATE',
        targetSection: 'CONTEXT',
        targetModule: module,
        weight: 'advisory',
        reason: element.language === 'bash' || element.language === 'sh'
          ? 'Build/tool commands'
          : 'Code reference',
        routingTrace,
      };
    }

    case 'table-row': {
      return {
        decision: 'MIGRATE',
        targetSection: 'CONTEXT',
        targetModule: module,
        weight: 'advisory',
        reason: 'Tabular reference data',
        routingTrace,
      };
    }

    case 'table-block': {
      return {
        decision: 'MIGRATE',
        targetSection: 'CONTEXT',
        targetModule: module,
        weight: 'advisory',
        reason: 'Tabular reference data (block)',
        routingTrace,
      };
    }

    case 'prose': {
      // Architecture descriptions → CONTEXT
      if (/\b(architect|depend|flow|package|modul|struct|layer)\b/i.test(text)) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONTEXT',
          targetModule: module,
          weight: 'advisory',
          reason: 'Architecture description',
          routingTrace,
        };
      }
      // Directory/config descriptions → CONTEXT
      if (/\b(director|config|\.charter|\.ai)\b/i.test(text)) {
        return {
          decision: 'MIGRATE',
          targetSection: 'CONTEXT',
          targetModule: module,
          weight: 'advisory',
          reason: 'Configuration/structure description',
          routingTrace,
        };
      }
      // Default prose → CONTEXT (never silently dropped)
      return {
        decision: 'MIGRATE',
        targetSection: 'CONTEXT',
        targetModule: module,
        weight: 'advisory',
        reason: 'Informational context',
        routingTrace,
      };
    }
  }
}

// ============================================================================
// Deduplication
// ============================================================================

/**
 * Check if two text items are duplicates using Jaccard similarity.
 * Threshold: 0.8 (80% word overlap = duplicate).
 */
export function isDuplicateItem(existing: string, candidate: string): boolean {
  const setA = new Set(tokenize(existing));
  const setB = new Set(tokenize(candidate));

  if (setA.size === 0 && setB.size === 0) return true;
  if (setA.size === 0 || setB.size === 0) return false;

  let intersection = 0;
  for (const word of setA) {
    if (setB.has(word)) intersection++;
  }

  const union = setA.size + setB.size - intersection;
  return union > 0 && intersection / union >= 0.8;
}

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 1);
}

// ============================================================================
// Migration Plan Builder
// ============================================================================

/**
 * Build a complete migration plan from parsed markdown sections.
 *
 * If existingAdf is provided, uses Jaccard dedup to skip items already present.
 */
export function buildMigrationPlan(
  sections: MarkdownSection[],
  existingAdf?: AdfDocument,
  triggerMap?: TriggerMap,
  config?: ClassifierConfig,
): MigrationPlan {
  const items: MigrationItem[] = [];

  // Collect existing ADF content for dedup
  const existingItems = new Set<string>();
  if (existingAdf) {
    for (const section of existingAdf.sections) {
      if (section.content.type === 'list') {
        for (const item of section.content.items) {
          existingItems.add(item);
        }
      } else if (section.content.type === 'text') {
        existingItems.add(section.content.value);
      }
    }
  }

  for (const section of sections) {
    for (const element of section.elements) {
      const classification = classifyElement(element, section.heading, triggerMap, config);

      // Dedup against existing ADF
      if (classification.decision === 'MIGRATE' && existingItems.size > 0) {
        const isDup = [...existingItems].some(existing =>
          isDuplicateItem(existing, element.content)
        );
        if (isDup) {
          // Still track as STAY (already migrated)
          items.push({
            element,
            sourceHeading: section.heading,
            classification: {
              ...classification,
              decision: 'STAY',
              reason: 'Already exists in ADF (deduplicated)',
            },
          });
          continue;
        }
      }

      items.push({
        element,
        sourceHeading: section.heading,
        classification,
      });
    }
  }

  // Sibling coherence: items sharing a sourceHeading route to the majority module
  const headingGroups = new Map<string, MigrationItem[]>();
  for (const item of items) {
    if (item.classification.decision !== 'MIGRATE') continue;
    const key = item.sourceHeading;
    if (!headingGroups.has(key)) headingGroups.set(key, []);
    headingGroups.get(key)!.push(item);
  }
  for (const [, group] of headingGroups) {
    if (group.length < 2) continue;
    const counts = new Map<string, number>();
    for (const it of group) {
      const m = it.classification.targetModule;
      counts.set(m, (counts.get(m) || 0) + 1);
    }
    const majority = [...counts.entries()].sort((a, b) => b[1] - a[1])[0][0];
    for (const it of group) {
      if (it.classification.targetModule !== majority) {
        it.classification.targetModule = majority;
        it.classification.reason += ' (sibling-coherence)';
      }
    }
  }

  const stayItems = items.filter(i => i.classification.decision === 'STAY');
  const migrateItems = items.filter(i => i.classification.decision === 'MIGRATE');
  const targetModules = [...new Set(migrateItems.map(i => i.classification.targetModule))];

  return {
    items,
    stayItems,
    migrateItems,
    targetModules,
    summary: {
      constraints: migrateItems.filter(i => i.classification.targetSection === 'CONSTRAINTS').length,
      context: migrateItems.filter(i => i.classification.targetSection === 'CONTEXT').length,
      advisory: migrateItems.filter(i => i.classification.targetSection === 'ADVISORY').length,
      stay: stayItems.length,
      total: items.length,
    },
  };
}
