name: Bug report
description: Report a reproducible defect in Charter Kit
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue. Please include enough detail to reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands and inputs used.
      placeholder: |
        1. Run `...`
        2. Run `...`
        3. Observe `...`
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Command output / logs
      description: Include relevant text output, JSON output, and exit code.
      render: shell
  - type: input
    id: version
    attributes:
      label: Charter version
      placeholder: e.g. 0.1.0 (`charter --version`)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: e.g. 22.17.0 (`node -v`)
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I verified this on the latest main branch or latest release.
          required: true
        - label: I searched existing issues before filing this report.
          required: true
