/**
 * @stackbilt/ci — GitHub Actions helpers
 *
 * Provides formatting utilities for GitHub Actions output:
 * - Status check annotations
 * - PR comment formatting
 * - GITHUB_OUTPUT helpers
 *
 * These are utility functions used by the GitHub Action workflow.
 * The actual workflow YAML is in the repo root at .github/actions/.
 */

import type { DriftViolation, GitValidationStatus } from '@stackbilt/types';

// ============================================================================
// GitHub Actions Output
// ============================================================================

/**
 * Write a GitHub Actions output variable.
 */
export function setOutput(name: string, value: string): void {
  const outputFile = process.env.GITHUB_OUTPUT;
  if (outputFile) {
    const fs = require('node:fs');
    fs.appendFileSync(outputFile, `${name}=${value}\n`);
  }
}

/**
 * Write a GitHub Actions step summary.
 */
export function setSummary(markdown: string): void {
  const summaryFile = process.env.GITHUB_STEP_SUMMARY;
  if (summaryFile) {
    const fs = require('node:fs');
    fs.appendFileSync(summaryFile, markdown + '\n');
  }
}

// ============================================================================
// Annotations
// ============================================================================

/**
 * Emit GitHub Actions annotations for drift violations.
 * Shows inline warnings/errors on PR file diffs.
 */
export function annotateDriftViolations(violations: DriftViolation[]): void {
  for (const v of violations) {
    const level = v.severity === 'BLOCKER' || v.severity === 'CRITICAL' ? 'error' : 'warning';
    // GitHub Actions annotation format
    console.log(`::${level} file=${v.file},line=${v.line}::${v.patternName}: ${v.snippet}`);
  }
}

/**
 * Emit a GitHub Actions annotation for validation status.
 */
export function annotateValidationStatus(
  status: GitValidationStatus,
  summary: string
): void {
  if (status === 'FAIL') {
    console.log(`::error::Governance validation failed: ${summary}`);
  } else if (status === 'WARN') {
    console.log(`::warning::Governance validation warning: ${summary}`);
  }
}

// ============================================================================
// PR Comment Formatting
// ============================================================================

/**
 * Format a governance check result as a PR comment body.
 */
export function formatPRComment(result: {
  status: string;
  summary: string;
  violations?: DriftViolation[];
  suggestions?: string[];
  score?: number;
}): string {
  const icon = result.status === 'PASS' ? '✅'
    : result.status === 'WARN' ? '⚠️'
    : '❌';

  const lines: string[] = [
    `## ${icon} Charter Governance Check`,
    '',
    `**Status:** ${result.status}`,
    `**Summary:** ${result.summary}`,
  ];

  if (result.score !== undefined) {
    lines.push(`**Drift Score:** ${Math.round(result.score * 100)}%`);
  }

  if (result.violations && result.violations.length > 0) {
    lines.push('', '### Violations', '');
    lines.push('| File | Line | Pattern | Snippet |');
    lines.push('|------|------|---------|---------|');
    for (const v of result.violations.slice(0, 20)) {
      lines.push(`| \`${v.file}\` | ${v.line} | ${v.patternName} | \`${v.snippet.slice(0, 50)}\` |`);
    }
    if (result.violations.length > 20) {
      lines.push(`| ... | | | ${result.violations.length - 20} more violations |`);
    }
  }

  if (result.suggestions && result.suggestions.length > 0) {
    lines.push('', '### Suggestions', '');
    for (const s of result.suggestions) {
      lines.push(`- ${s}`);
    }
  }

  lines.push('', '---', '*Generated by [Charter](https://github.com/stackbilt-dev/charter-kit)*');

  return lines.join('\n');
}
