/**
 * CLI-level tests for `charter adf compile`.
 *
 * Tests:
 * - stdout rendering (single target)
 * - --write with overwrite protection (banner check, --force bypass)
 * - --check stale/current paths
 * - error handling (missing manifest, bad --target, mutually exclusive flags)
 * - JSON output format
 *
 * Uses temp-dir fixture .ai/ tree following the pattern of adf-init.test.ts.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { CLIOptions } from '../index';
import { adfCommand } from '../commands/adf';
import { COMPILE_BANNER_MARKER } from '@stackbilt/adf';

// ============================================================================
// Test helpers
// ============================================================================

const TEXT_OPTIONS: CLIOptions = {
  configPath: '.charter',
  format: 'text',
  ciMode: false,
  yes: false,
};

const JSON_OPTIONS: CLIOptions = {
  configPath: '.charter',
  format: 'json',
  ciMode: false,
  yes: false,
};

const originalCwd = process.cwd();
const tempDirs: string[] = [];

afterEach(() => {
  process.chdir(originalCwd);
  while (tempDirs.length > 0) {
    const dir = tempDirs.pop();
    if (dir) fs.rmSync(dir, { recursive: true, force: true });
  }
  vi.restoreAllMocks();
});

function makeTmp(): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'charter-compile-test-'));
  tempDirs.push(dir);
  process.chdir(dir);
  return dir;
}

/** Set up a minimal .ai/ fixture in the current tmpdir. */
function scaffoldAi(tmp: string, extra?: Record<string, string>): void {
  const aiDir = path.join(tmp, '.ai');
  fs.mkdirSync(aiDir, { recursive: true });

  fs.writeFileSync(path.join(aiDir, 'manifest.adf'), [
    'ADF: 0.1',
    '',
    '🎯 ROLE: Test project',
    '',
    '📦 DEFAULT_LOAD:',
    '  - core.adf',
    '  - state.adf',
    '',
    '📂 ON_DEMAND:',
    '  - frontend.adf (Triggers on: React, CSS)',
    '',
  ].join('\n'));

  fs.writeFileSync(path.join(aiDir, 'core.adf'), [
    'ADF: 0.1',
    '',
    '📋 CONTEXT:',
    '  - TypeScript monorepo',
    '',
    '⚠️ CONSTRAINTS [load-bearing]:',
    '  - No secrets in commits',
    '',
  ].join('\n'));

  fs.writeFileSync(path.join(aiDir, 'state.adf'), [
    'ADF: 0.1',
    '',
    '🧠 STATE:',
    '  CURRENT: Active development',
    '',
  ].join('\n'));

  for (const [filename, content] of Object.entries(extra ?? {})) {
    fs.writeFileSync(path.join(tmp, filename), content);
  }
}

function captureStdout(fn: () => Promise<number> | number): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: string[] = [];
    const orig = process.stdout.write.bind(process.stdout);
    process.stdout.write = (chunk: string | Uint8Array): boolean => {
      chunks.push(String(chunk));
      return true;
    };
    Promise.resolve(fn())
      .then(() => {
        process.stdout.write = orig;
        resolve(chunks.join(''));
      })
      .catch(err => {
        process.stdout.write = orig;
        reject(err);
      });
  });
}

function captureLog(fn: () => Promise<number> | number): Promise<string[]> {
  return new Promise((resolve, reject) => {
    const captured: string[] = [];
    const spy = vi.spyOn(console, 'log').mockImplementation((s: string) => captured.push(s));
    Promise.resolve(fn())
      .then(() => {
        spy.mockRestore();
        resolve(captured);
      })
      .catch(err => {
        spy.mockRestore();
        reject(err);
      });
  });
}

// ============================================================================
// Stdout mode (no --write / --check)
// ============================================================================

describe('adf compile — stdout mode', () => {
  it('prints compiled output to stdout for a single target', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const output = await captureStdout(() =>
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude']),
    );

    expect(output).toContain(COMPILE_BANNER_MARKER);
    expect(output).toContain('# CLAUDE.md');
    expect(output).toContain('## CONTEXT');
    expect(output).toContain('TypeScript monorepo');
  });

  it('cursor target uses hash comment banner', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const output = await captureStdout(() =>
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'cursor']),
    );

    expect(output).toMatch(/^# GENERATED by/);
    expect(output).not.toMatch(/^<!--/);
  });

  it('throws when --target all used without --write or --check', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await expect(
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all']),
    ).rejects.toThrow('requires --write or --check');
  });

  it('throws on invalid --target', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await expect(
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'copilot']),
    ).rejects.toThrow('Invalid --target');
  });

  it('throws when --target missing', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await expect(
      adfCommand(TEXT_OPTIONS, ['compile']),
    ).rejects.toThrow('--target');
  });

  it('throws when manifest.adf not found', async () => {
    makeTmp(); // no scaffoldAi

    await expect(
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude']),
    ).rejects.toThrow('manifest.adf not found');
  });

  it('throws on --write and --check together', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await expect(
      adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write', '--check']),
    ).rejects.toThrow('mutually exclusive');
  });
});

// ============================================================================
// JSON stdout mode
// ============================================================================

describe('adf compile — JSON stdout mode', () => {
  it('emits JSON with target, output, modules, nextActions', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const logs = await captureLog(() =>
      adfCommand(JSON_OPTIONS, ['compile', '--target', 'claude']),
    );

    const result = JSON.parse(logs[0]);
    expect(result.target).toBe('claude');
    expect(result.output).toContain(COMPILE_BANNER_MARKER);
    expect(result.defaultModules).toEqual(['core.adf', 'state.adf']);
    expect(result.onDemandModules).toHaveLength(1);
    expect(result.onDemandModules[0].path).toBe('frontend.adf');
    expect(result.nextActions).toBeDefined();
    expect(Array.isArray(result.nextActions)).toBe(true);
  });
});

// ============================================================================
// --write mode
// ============================================================================

describe('adf compile — --write mode', () => {
  it('writes CLAUDE.md to the working directory', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);

    expect(exitCode).toBe(0);
    const written = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(written).toContain(COMPILE_BANNER_MARKER);
    expect(written).toContain('## CONTEXT');
  });

  it('writes .cursorrules with hash banner for cursor target', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'cursor', '--write']);

    const written = fs.readFileSync(path.join(tmp, '.cursorrules'), 'utf-8');
    expect(written).toMatch(/^# GENERATED by/);
  });

  it('--target all writes all four files', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const exitCode = await adfCommand(TEXT_OPTIONS, [
      'compile', '--target', 'all', '--write',
    ]);

    expect(exitCode).toBe(0);
    expect(fs.existsSync(path.join(tmp, 'CLAUDE.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'AGENTS.md'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, '.cursorrules'))).toBe(true);
    expect(fs.existsSync(path.join(tmp, 'GEMINI.md'))).toBe(true);
  });

  it('refuses to overwrite a file without the compile banner (hand-written)', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // Hand-written file — no compile banner
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), '# My hand-written CLAUDE.md\n\nDo not overwrite me.\n');

    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);
    spy.mockRestore();

    // Should be refused — exit 1 (POLICY_VIOLATION)
    expect(exitCode).toBe(1);
    // Original file should be unchanged
    const content = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(content).toBe('# My hand-written CLAUDE.md\n\nDo not overwrite me.\n');
  });

  it('refuses to overwrite pointer stubs without --force', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // Pointer stub from `adf init --emit-pointers` — no compile banner
    const pointerStub = '# CLAUDE.md\n\n> **DO NOT add rules, constraints, or context to this file.**\n';
    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), pointerStub);

    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);
    spy.mockRestore();

    expect(exitCode).toBe(1);
    const content = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(content).toBe(pointerStub);
  });

  it('--force overwrites a file without the compile banner', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    fs.writeFileSync(path.join(tmp, 'CLAUDE.md'), '# Old hand-written content\n');

    const exitCode = await adfCommand(TEXT_OPTIONS, [
      'compile', '--target', 'claude', '--write', '--force',
    ]);

    expect(exitCode).toBe(0);
    const content = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain(COMPILE_BANNER_MARKER);
  });

  it('overwrites an existing compile artifact without --force', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // First write
    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);
    // Second write — should succeed without --force since banner is present
    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);

    expect(exitCode).toBe(0);
    const content = fs.readFileSync(path.join(tmp, 'CLAUDE.md'), 'utf-8');
    expect(content).toContain(COMPILE_BANNER_MARKER);
  });

  it('--write JSON output lists written files and nextActions', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const logs = await captureLog(() =>
      adfCommand(JSON_OPTIONS, ['compile', '--target', 'claude', '--write']),
    );

    const result = JSON.parse(logs[0]);
    expect(result.written).toContain('CLAUDE.md');
    expect(result.refused).toEqual([]);
    expect(Array.isArray(result.nextActions)).toBe(true);
  });
});

// ============================================================================
// --check mode
// ============================================================================

describe('adf compile — --check mode', () => {
  it('exits 0 when compiled output matches file on disk', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // First write the file so it matches
    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);

    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--check']);
    expect(exitCode).toBe(0);
  });

  it('exits 1 when file on disk is stale', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // Write a stale / hand-modified version
    fs.writeFileSync(
      path.join(tmp, 'CLAUDE.md'),
      `<!-- ${COMPILE_BANNER_MARKER} -->\n\n# CLAUDE.md\n\nStale content that differs.\n`,
    );

    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--check']);
    expect(exitCode).toBe(1);
  });

  it('exits 1 when file does not exist on disk', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--check']);
    expect(exitCode).toBe(1);
  });

  it('--target all exits 0 when all files are current', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all', '--write']);
    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all', '--check']);
    expect(exitCode).toBe(0);
  });

  it('--target all exits 1 when any file is stale', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all', '--write']);
    // Corrupt one file
    const agentsMd = path.join(tmp, 'AGENTS.md');
    fs.writeFileSync(agentsMd, fs.readFileSync(agentsMd, 'utf-8') + '\n# Extra stale content\n');

    const exitCode = await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all', '--check']);
    expect(exitCode).toBe(1);
  });

  it('--check JSON output reports stale/current/missing arrays', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    // Write CLAUDE.md but leave AGENTS.md missing
    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'claude', '--write']);

    const logs = await captureLog(() =>
      adfCommand(JSON_OPTIONS, ['compile', '--target', 'all', '--check']),
    );

    const result = JSON.parse(logs[0]);
    expect(result.current).toContain('CLAUDE.md');
    expect(result.missing).toContain('AGENTS.md');
    expect(result.upToDate).toBe(false);
    expect(Array.isArray(result.nextActions)).toBe(true);
  });

  it('--check JSON output sets upToDate true when all current', async () => {
    const tmp = makeTmp();
    scaffoldAi(tmp);

    await adfCommand(TEXT_OPTIONS, ['compile', '--target', 'all', '--write']);

    const logs = await captureLog(() =>
      adfCommand(JSON_OPTIONS, ['compile', '--target', 'all', '--check']),
    );

    const result = JSON.parse(logs[0]);
    expect(result.upToDate).toBe(true);
    expect(result.stale).toEqual([]);
    expect(result.missing).toEqual([]);
  });
});
