/**
 * Tests for the ADF compiler — the outbound direction of the ADF toolchain.
 *
 * All tests use injected readFile to avoid touching disk.
 * Fixture .ai/ tree is set up in-memory to match how bundler.test.ts works.
 */

import { describe, it, expect } from 'vitest';
import {
  compileAdf,
  buildBanner,
  COMPILE_BANNER_MARKER,
  COMPILE_TARGETS,
  MODULE_INDEX_FENCE,
  TARGET_FILENAMES,
} from '../compiler';
import type { CompileOptions } from '../compiler';

// ============================================================================
// Fixtures
// ============================================================================

const MANIFEST_ADF = `ADF: 0.1
🎯 ROLE: Test project context router

📦 DEFAULT_LOAD:
  - core.adf
  - state.adf

📂 ON_DEMAND:
  - frontend.adf (Triggers on: React, CSS, UI)
  - backend.adf (Triggers on: API, Node, DB)

📐 RULES:
  - Prefer smallest relevant module set.
  - Never assume unseen modules were loaded.
`;

const CORE_ADF = `ADF: 0.1

📋 CONTEXT:
  - TypeScript monorepo
  - pnpm workspaces

⚠️ CONSTRAINTS [load-bearing]:
  - No secrets in commits
  - Use conventional commits

📊 METRICS [load-bearing]:
  entry_loc: 142 / 200 [lines]
`;

const STATE_ADF = `ADF: 0.1

🧠 STATE:
  CURRENT: Active development
  NEXT: Ship v1.0
`;

const FILES: Record<string, string> = {
  '/ai/manifest.adf': MANIFEST_ADF,
  '/ai/core.adf': CORE_ADF,
  '/ai/state.adf': STATE_ADF,
};

function makeReadFile(files: Record<string, string>): (p: string) => string {
  return (p: string): string => {
    const content = files[p];
    if (content === undefined) throw new Error(`File not found: ${p}`);
    return content;
  };
}

function makeOptions(target: CompileOptions['target'], extra?: Record<string, string>): CompileOptions {
  return {
    target,
    aiDir: '/ai',
    readFile: makeReadFile({ ...FILES, ...extra }),
  };
}

// ============================================================================
// buildBanner
// ============================================================================

describe('buildBanner', () => {
  it('returns an HTML comment for html style', () => {
    const banner = buildBanner('html');
    expect(banner.startsWith('<!--')).toBe(true);
    expect(banner.endsWith('-->')).toBe(true);
    expect(banner).toContain(COMPILE_BANNER_MARKER);
  });

  it('returns a hash comment for hash style', () => {
    const banner = buildBanner('hash');
    expect(banner).toMatch(/^#\s/);
    expect(banner).toContain(COMPILE_BANNER_MARKER);
  });

  it('html banner does not use # prefix', () => {
    const banner = buildBanner('html');
    expect(banner).not.toMatch(/^#/);
  });
});

// ============================================================================
// compileAdf — banner
// ============================================================================

describe('compileAdf — banner', () => {
  it('claude target starts with html comment banner', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toMatch(/^<!--/);
    expect(result.output).toContain(COMPILE_BANNER_MARKER);
  });

  it('agents target starts with html comment banner', () => {
    const result = compileAdf(makeOptions('agents'));
    expect(result.output).toMatch(/^<!--/);
    expect(result.output).toContain(COMPILE_BANNER_MARKER);
  });

  it('cursor target starts with hash comment banner', () => {
    const result = compileAdf(makeOptions('cursor'));
    expect(result.output).toMatch(/^# GENERATED by/);
    expect(result.output).not.toMatch(/^<!--/);
    expect(result.output).toContain(COMPILE_BANNER_MARKER);
  });

  it('gemini target starts with html comment banner', () => {
    const result = compileAdf(makeOptions('gemini'));
    expect(result.output).toMatch(/^<!--/);
    expect(result.output).toContain(COMPILE_BANNER_MARKER);
  });
});

// ============================================================================
// compileAdf — per-target title
// ============================================================================

describe('compileAdf — title', () => {
  it('claude target has # CLAUDE.md title', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('# CLAUDE.md');
  });

  it('agents target has # AGENTS.md title', () => {
    const result = compileAdf(makeOptions('agents'));
    expect(result.output).toContain('# AGENTS.md');
  });

  it('cursor target has # .cursorrules title', () => {
    const result = compileAdf(makeOptions('cursor'));
    expect(result.output).toContain('# .cursorrules');
  });

  it('gemini target has # GEMINI.md title', () => {
    const result = compileAdf(makeOptions('gemini'));
    expect(result.output).toContain('# GEMINI.md');
  });
});

// ============================================================================
// compileAdf — role from manifest
// ============================================================================

describe('compileAdf — manifest role', () => {
  it('includes manifest ROLE as a blockquote', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('> Test project context router');
  });

  it('omits blockquote when manifest has no ROLE', () => {
    const noRole = MANIFEST_ADF.replace(/🎯 ROLE: Test project context router\n\n/, '');
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({ ...FILES, '/ai/manifest.adf': noRole }),
    });
    expect(result.output).not.toContain('> ');
  });
});

// ============================================================================
// compileAdf — default module content
// ============================================================================

describe('compileAdf — default module content', () => {
  it('renders CONTEXT section from core.adf', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('## CONTEXT');
    expect(result.output).toContain('TypeScript monorepo');
  });

  it('renders CONSTRAINTS section with weight annotation', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('## CONSTRAINTS _(load-bearing)_');
    expect(result.output).toContain('No secrets in commits');
  });

  it('renders METRICS section from core.adf', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('## METRICS _(load-bearing)_');
    expect(result.output).toContain('`entry_loc`: 142 / 200 [lines]');
  });

  it('renders STATE section from state.adf', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('## STATE');
    expect(result.output).toContain('Active development');
  });

  it('modules are rendered in declaration order (core before state)', () => {
    const result = compileAdf(makeOptions('claude'));
    const contextPos = result.output.indexOf('## CONTEXT');
    const statePos = result.output.indexOf('## STATE');
    expect(contextPos).toBeLessThan(statePos);
  });
});

// ============================================================================
// compileAdf — manifest-only sections excluded
// ============================================================================

describe('compileAdf — manifest-only sections excluded', () => {
  it('does not include DEFAULT_LOAD section in output', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).not.toContain('## DEFAULT_LOAD');
  });

  it('does not include ON_DEMAND section in output', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).not.toContain('## ON_DEMAND');
  });

  it('does not include DEFAULT_LOAD routing plumbing in output', () => {
    const result = compileAdf(makeOptions('claude'));
    // Verify manifest routing plumbing is skipped (these are in manifest.adf, not content modules)
    expect(result.output).not.toContain('## DEFAULT_LOAD');
    expect(result.output).not.toContain('## ON_DEMAND');
    expect(result.output).not.toContain('## BUDGET');
  });

  it('does not inline on-demand module bodies', () => {
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({
        ...FILES,
        '/ai/frontend.adf': 'ADF: 0.1\nCONSTRAINTS:\n  - Use React hooks\n',
      }),
    });
    // The on-demand module body should NOT appear as compiled content
    expect(result.output).not.toContain('Use React hooks');
  });
});

// ============================================================================
// compileAdf — on-demand listing
// ============================================================================

describe('compileAdf — on-demand module index (spec §4.2)', () => {
  it('wraps the index in agents-modules HTML comment fences for markdown targets', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain(`<!-- ${MODULE_INDEX_FENCE} -->`);
    expect(result.output).toContain(`<!-- /${MODULE_INDEX_FENCE} -->`);
    expect(result.output).toContain('## Additional instructions');
    expect(result.output).toContain('Read the matching file before working in these areas:');
  });

  it('uses hash-style fences for the cursor target', () => {
    const result = compileAdf(makeOptions('cursor'));
    expect(result.output).toContain(`# ${MODULE_INDEX_FENCE}`);
    expect(result.output).toContain(`# /${MODULE_INDEX_FENCE}`);
    expect(result.output).not.toContain(`<!-- ${MODULE_INDEX_FENCE} -->`);
  });

  it('lists each on-demand module with its aiDir-prefixed path and triggers', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toContain('`/ai/frontend.adf` — Triggers: React, CSS, UI');
    expect(result.output).toContain('`/ai/backend.adf` — Triggers: API, Node, DB');
  });

  it('omits the index when no on-demand modules exist', () => {
    const noOnDemand = `ADF: 0.1

📦 DEFAULT_LOAD:
  - core.adf
`;
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({ ...FILES, '/ai/manifest.adf': noOnDemand }),
    });
    expect(result.output).not.toContain(MODULE_INDEX_FENCE);
    expect(result.output).not.toContain('## Additional instructions');
  });

  it('lists on-demand modules without triggers (no trigger string)', () => {
    const manifestNoTriggers = `ADF: 0.1

📦 DEFAULT_LOAD:
  - core.adf

📂 ON_DEMAND:
  - extras.adf
`;
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({ ...FILES, '/ai/manifest.adf': manifestNoTriggers }),
    });
    expect(result.output).toContain('`/ai/extras.adf`');
    // No trigger annotation for modules without triggers
    expect(result.output).not.toContain('extras.adf` — Triggers:');
  });
});

// ============================================================================
// compileAdf — determinism
// ============================================================================

describe('compileAdf — determinism', () => {
  it('produces byte-identical output on repeated calls with same input', () => {
    const opts = makeOptions('claude');
    const first = compileAdf(opts).output;
    const second = compileAdf(opts).output;
    expect(first).toBe(second);
  });

  it('produces byte-identical output across all targets for same content', () => {
    // Content should differ only in banner style and title
    const claude = compileAdf(makeOptions('claude')).output;
    const agents = compileAdf(makeOptions('agents')).output;
    // Body content after the banner+title should be the same
    const extractBody = (out: string): string =>
      out.split('\n').slice(4).join('\n'); // skip banner + blank + title + blank
    expect(extractBody(claude)).toBe(extractBody(agents));
  });

  it('output ends with exactly one newline', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.output).toMatch(/\n$/);
    expect(result.output).not.toMatch(/\n\n$/);
  });
});

// ============================================================================
// compileAdf — result metadata
// ============================================================================

describe('compileAdf — result metadata', () => {
  it('returns correct target in result', () => {
    const result = compileAdf(makeOptions('cursor'));
    expect(result.target).toBe('cursor');
  });

  it('returns list of default modules', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.defaultModules).toEqual(['core.adf', 'state.adf']);
  });

  it('returns list of on-demand modules with triggers', () => {
    const result = compileAdf(makeOptions('claude'));
    expect(result.onDemandModules).toHaveLength(2);
    expect(result.onDemandModules[0].path).toBe('frontend.adf');
    expect(result.onDemandModules[0].triggers).toEqual(['React', 'CSS', 'UI']);
  });
});

// ============================================================================
// compileAdf — content rendering edge cases
// ============================================================================

describe('compileAdf — content rendering edge cases', () => {
  it('renders map-type section as bold-key list', () => {
    const withMap = `ADF: 0.1

📦 DEFAULT_LOAD:
  - module.adf
`;
    const module = `ADF: 0.1

🧠 STATE:
  CURRENT: Working
  NEXT: Ship it
`;
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({
        '/ai/manifest.adf': withMap,
        '/ai/module.adf': module,
      }),
    });
    expect(result.output).toContain('## STATE');
    expect(result.output).toContain('**CURRENT**: Working');
    expect(result.output).toContain('**NEXT**: Ship it');
  });

  it('renders metric-type section as code-key list', () => {
    const result = compileAdf(makeOptions('claude'));
    // METRICS section from core.adf is metric type
    expect(result.output).toMatch(/`entry_loc`: \d+ \/ \d+ \[lines\]/);
  });

  it('renders text-type section as plain text', () => {
    const withText = `ADF: 0.1

📦 DEFAULT_LOAD:
  - module.adf
`;
    const module = `ADF: 0.1

📋 CONTEXT: TypeScript monorepo with pnpm workspaces
`;
    const result = compileAdf({
      target: 'claude',
      aiDir: '/ai',
      readFile: makeReadFile({
        '/ai/manifest.adf': withText,
        '/ai/module.adf': module,
      }),
    });
    expect(result.output).toContain('## CONTEXT');
    expect(result.output).toContain('TypeScript monorepo with pnpm workspaces');
  });
});

// ============================================================================
// Constants
// ============================================================================

describe('COMPILE_TARGETS and TARGET_FILENAMES', () => {
  it('COMPILE_TARGETS includes all four targets', () => {
    expect(COMPILE_TARGETS).toContain('claude');
    expect(COMPILE_TARGETS).toContain('agents');
    expect(COMPILE_TARGETS).toContain('cursor');
    expect(COMPILE_TARGETS).toContain('gemini');
    expect(COMPILE_TARGETS).toHaveLength(4);
  });

  it('TARGET_FILENAMES maps each target to the correct filename', () => {
    expect(TARGET_FILENAMES.claude).toBe('CLAUDE.md');
    expect(TARGET_FILENAMES.agents).toBe('AGENTS.md');
    expect(TARGET_FILENAMES.cursor).toBe('.cursorrules');
    expect(TARGET_FILENAMES.gemini).toBe('GEMINI.md');
  });
});
